---
language: go

services:
  - docker 

notifications:
  email: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y rpm

script:
  - make tests
  

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  matrix:
    - GO111MODULE=on
