---
language: go

sudo: required

services:
  - docker 

notifications:
  email: false

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y rpm

script:
  - GO111MODULE=on go test ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
  

after_success:
  - bash <(curl -s https://codecov.io/bash)

env:
  matrix:
    - GO111MODULE=on
