---
## Controls Files.
# These are YAML files that hold all the details for running checks.
# In here you can set all parameter substitution for docker-bench

docker-storage:
  value: /var/lib/docker
